# app.py

import streamlit as st
from model import GPT2PPLV2 as GPT2PPL
import torch

# Initialize the GPT2PPL model
model = GPT2PPL()

# Streamlit UI components
st.title("AI Text Detection")
st.write("Enter your text to determine whether it's likely written by an AI or a human.")

# Text input area with adjustable height
sentence = st.text_area(
    "Input your text here:",
    height=200,  # You can adjust the default height
    help="You can drag the bottom-right corner to resize the box."  # Informative tooltip
)

# Chunk value (optional, depends on your original code)
chunk_value = 100  # You can adjust this based on your model's expectation

# Process button
if st.button("Process"):
    if not sentence.strip():
        st.warning("Please enter some text to process.")
    else:
        # Call the model
        with st.spinner("Processing..."):
            result, verdict = model(sentence, chunk_value, "v1.1")

        # Display the results
        st.write("Results:")
        st.write("Probability:", result["prob"])
        st.write("Verdict:", verdict)

        if result["label"] == 0:
            st.success("This text is most likely generated by an AI.")
        else:
            st.success("This text is most likely written by a human.")
